// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteManagement.Data.Context;

#nullable disable

namespace SiteManagement.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SiteManagement.Entity.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SiteId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("126c039b-8731-439f-96c5-0f06b7eda003"),
                            Content = "Ocak 2024 dönemi aidat ödemeleri 31 Ocak'a kadar yapılmalıdır.",
                            CreatedBy = "seed",
                            CreatedById = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            Title = "Ocak Ayı Aidat Bildirimi"
                        },
                        new
                        {
                            Id = new Guid("275eadcc-2f61-41b7-82a6-80c7bb24a85d"),
                            Content = "15 Ocak 2024 tarihinde 09:00-17:00 saatleri arasında bakım nedeniyle su kesintisi yaşanacaktır.",
                            CreatedBy = "seed",
                            CreatedById = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            Title = "Su Kesintisi Duyurusu"
                        },
                        new
                        {
                            Id = new Guid("d4be6e28-d3cd-4f06-afc0-1e3afed68cff"),
                            Content = "20 Ocak 2024 Cumartesi saat 14:00'te site toplantı salonunda genel kurul yapılacaktır.",
                            CreatedBy = "seed",
                            CreatedById = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            CreatedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            SiteId = new Guid("ef55ed67-b6ae-4746-8b94-6e48a0f61a49"),
                            Title = "Genel Kurul Toplantısı"
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("SiteId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SquareMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SiteId");

                    b.HasIndex("TenantId");

                    b.ToTable("Apartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c38f383-b67d-4f6c-8a75-ff57c58621b5"),
                            ApartmentNumber = "1",
                            BlockId = new Guid("448d9760-5b48-450d-8297-c25c88e7be2f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Floor = 1,
                            IsDeleted = false,
                            IsRented = false,
                            OwnerId = new Guid("44010978-e210-4db8-81e9-6f191695953b"),
                            RoomCount = 3,
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            SquareMeters = 120m
                        },
                        new
                        {
                            Id = new Guid("b2823418-628c-4bce-848a-4032abb0feaf"),
                            ApartmentNumber = "2",
                            BlockId = new Guid("448d9760-5b48-450d-8297-c25c88e7be2f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Floor = 1,
                            IsDeleted = false,
                            IsRented = true,
                            OwnerId = new Guid("44010978-e210-4db8-81e9-6f191695953b"),
                            RoomCount = 2,
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            SquareMeters = 90m,
                            TenantId = new Guid("e60285cb-58df-4960-ba9f-d5bbd5116195")
                        },
                        new
                        {
                            Id = new Guid("825472e5-0820-46cd-9039-b1565befd726"),
                            ApartmentNumber = "3",
                            BlockId = new Guid("41712748-f3e8-4540-9f19-200e5a1f095d"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Floor = 2,
                            IsDeleted = false,
                            IsRented = false,
                            OwnerId = new Guid("c725e0e7-d8c1-4ac7-b9ac-d580cd22aa1d"),
                            RoomCount = 4,
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            SquareMeters = 150m
                        },
                        new
                        {
                            Id = new Guid("e5739a46-573e-4252-b610-060e0a4ef016"),
                            ApartmentNumber = "1",
                            BlockId = new Guid("accf19a5-b677-4e03-996e-ef32eb2c93d5"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Floor = 1,
                            IsDeleted = false,
                            IsRented = true,
                            OwnerId = new Guid("c725e0e7-d8c1-4ac7-b9ac-d580cd22aa1d"),
                            RoomCount = 3,
                            SiteId = new Guid("ef55ed67-b6ae-4746-8b94-6e48a0f61a49"),
                            SquareMeters = 110m,
                            TenantId = new Guid("589da78a-0fd1-4fdf-bdde-4bf626b0b2df")
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("813c1780-e84a-4992-9676-2da6e6bb38df"),
                            ConcurrencyStamp = "e247d7d6-c166-4bef-9ff6-f4ac82ffe275",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("8407beb3-e2b8-483d-b7c5-f159327aa74b"),
                            ConcurrencyStamp = "a30bb6b1-5a37-42f0-8bf5-731514504352",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("44a9b0b3-9df5-4b85-83ac-608abfe46207"),
                            ConcurrencyStamp = "4d738c2c-b227-4681-8c77-37cb6ffb772f",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("45f843cb-d1e5-4a6b-afa3-3ab105d3b159"),
                            ConcurrencyStamp = "6dd9419e-2fcf-4503-8eaf-ff17ec107906",
                            Name = "Tenant",
                            NormalizedName = "TENANT"
                        },
                        new
                        {
                            Id = new Guid("066247ba-ca2c-4554-9311-bd96d8658923"),
                            ConcurrencyStamp = "da45abd6-f019-4b8e-9efe-c6360447b981",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6b6ce5a-93ac-44d1-936b-ed80b6f9b04f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c598451-1b3e-4fef-ae98-5e5cedc1fb19",
                            Email = "admin@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SITEYONETIM.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJk8qS/lbvHdl7LLFJhRT2qhr+yUG9I/ixLuF1UgVrkdVGXTKDZirPpNWVhdLQipmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc97d115-a5d6-45ad-a8c7-741726348d6a",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53707e20-2eba-48cc-a252-82692c18e207",
                            Email = "ahmet@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@SITEYONETIM.COM",
                            NormalizedUserName = "AHMET.YILMAZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEIUNvi3S4EoJT1cfy+yIbqmv3znEkn5KhNGpp/UuLLYekBoneoIQ4z4iMSOMUhHv5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45db9a5e-1198-4cab-a6da-9f2655085592",
                            TwoFactorEnabled = false,
                            UserName = "ahmet.yilmaz"
                        },
                        new
                        {
                            Id = new Guid("44010978-e210-4db8-81e9-6f191695953b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22adbdde-8f90-4fe7-aa80-d8a2f731936a",
                            Email = "mehmet@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "Mehmet",
                            LastName = "Kaya",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHMET@SITEYONETIM.COM",
                            NormalizedUserName = "MEHMET.KAYA",
                            PasswordHash = "AQAAAAEAACcQAAAAEHutHVQtRjRQf+ivN4bL9Y7Uzt/qX5WRaXhKBMURMf8AWeHh15ZjEU0fQ08DEf0Sdg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dbb079-6248-4d7a-8518-6c9bf04a5ec1",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.kaya"
                        },
                        new
                        {
                            Id = new Guid("c725e0e7-d8c1-4ac7-b9ac-d580cd22aa1d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1227ac2-82c4-48c2-97ac-3d2f30d344a2",
                            Email = "ayse@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "Ayşe",
                            LastName = "Demir",
                            LockoutEnabled = false,
                            NormalizedEmail = "AYSE@SITEYONETIM.COM",
                            NormalizedUserName = "AYSE.DEMIR",
                            PasswordHash = "AQAAAAEAACcQAAAAEEtwUQO6QxFzwPUIApjhyep2ERXEZwEH/OCS1a89ArbFKJFFEXLrtC33DvPkhs9TZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57145f03-2dc7-4ce2-992f-ed8ff1226c45",
                            TwoFactorEnabled = false,
                            UserName = "ayse.demir"
                        },
                        new
                        {
                            Id = new Guid("e60285cb-58df-4960-ba9f-d5bbd5116195"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "786470ba-d779-41d5-a8bd-722f0b734de5",
                            Email = "ali@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            LastName = "Çelik",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI@SITEYONETIM.COM",
                            NormalizedUserName = "ALI.CELIK",
                            PasswordHash = "AQAAAAEAACcQAAAAEA2zDjpGbnJBhJ2P/OS1qLfHwvAr1tMyPbvNLFIwpSUYwXzrKy7m8u15G+BJeMEoGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4742ec2-19eb-43c2-814e-63364f357811",
                            TwoFactorEnabled = false,
                            UserName = "ali.celik"
                        },
                        new
                        {
                            Id = new Guid("589da78a-0fd1-4fdf-bdde-4bf626b0b2df"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b011fa0e-8aad-47c6-a253-868af88a11ba",
                            Email = "fatma@siteyonetim.com",
                            EmailConfirmed = true,
                            FirstName = "Fatma",
                            LastName = "Şahin",
                            LockoutEnabled = false,
                            NormalizedEmail = "FATMA@SITEYONETIM.COM",
                            NormalizedUserName = "FATMA.SAHIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHEicO2PBJsogJWLJRyQ0gW1Oor0HScnQJumnMA15b7QTa42EK/HhKC+OcR8L3rr4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d0c6685-1fc3-44c1-87e0-445382bc196b",
                            TwoFactorEnabled = false,
                            UserName = "fatma.sahin"
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c6b6ce5a-93ac-44d1-936b-ed80b6f9b04f"),
                            RoleId = new Guid("813c1780-e84a-4992-9676-2da6e6bb38df")
                        },
                        new
                        {
                            UserId = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            RoleId = new Guid("8407beb3-e2b8-483d-b7c5-f159327aa74b")
                        },
                        new
                        {
                            UserId = new Guid("44010978-e210-4db8-81e9-6f191695953b"),
                            RoleId = new Guid("44a9b0b3-9df5-4b85-83ac-608abfe46207")
                        },
                        new
                        {
                            UserId = new Guid("c725e0e7-d8c1-4ac7-b9ac-d580cd22aa1d"),
                            RoleId = new Guid("44a9b0b3-9df5-4b85-83ac-608abfe46207")
                        },
                        new
                        {
                            UserId = new Guid("e60285cb-58df-4960-ba9f-d5bbd5116195"),
                            RoleId = new Guid("45f843cb-d1e5-4a6b-afa3-3ab105d3b159")
                        },
                        new
                        {
                            UserId = new Guid("589da78a-0fd1-4fdf-bdde-4bf626b0b2df"),
                            RoleId = new Guid("45f843cb-d1e5-4a6b-afa3-3ab105d3b159")
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Blocks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("448d9760-5b48-450d-8297-c25c88e7be2f"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorCount = 8,
                            IsDeleted = false,
                            Name = "A Blok",
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480")
                        },
                        new
                        {
                            Id = new Guid("41712748-f3e8-4540-9f19-200e5a1f095d"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorCount = 6,
                            IsDeleted = false,
                            Name = "B Blok",
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480")
                        },
                        new
                        {
                            Id = new Guid("accf19a5-b677-4e03-996e-ef32eb2c93d5"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FloorCount = 10,
                            IsDeleted = false,
                            Name = "A Blok",
                            SiteId = new Guid("ef55ed67-b6ae-4746-8b94-6e48a0f61a49")
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("617015b4-00b8-4bac-84ea-f1d64dcbfd15"),
                            ApartmentId = new Guid("8c38f383-b67d-4f6c-8a75-ff57c58621b5"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A Blok asansörü 3 gündür çalışmıyor, lütfen en kısa sürede tamir edilsin.",
                            IsDeleted = false,
                            Status = 1,
                            Title = "Asansör Arızası",
                            UserId = new Guid("44010978-e210-4db8-81e9-6f191695953b")
                        },
                        new
                        {
                            Id = new Guid("a37349ef-cfce-4dd1-974b-39a6c673aab3"),
                            ApartmentId = new Guid("b2823418-628c-4bce-848a-4032abb0feaf"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kapalı otoparkın giriş katındaki aydınlatmalar çalışmıyor.",
                            IsDeleted = false,
                            Status = 0,
                            Title = "Otopark Işıkları",
                            UserId = new Guid("e60285cb-58df-4960-ba9f-d5bbd5116195")
                        },
                        new
                        {
                            Id = new Guid("e4cf0eb7-9930-4a38-bcda-82936cb82cfa"),
                            ApartmentId = new Guid("825472e5-0820-46cd-9039-b1565befd726"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Üst daireden gece geç saatlerde gürültü gelmektedir.",
                            IsDeleted = false,
                            Status = 2,
                            Title = "Gürültü Şikayeti",
                            UserId = new Guid("c725e0e7-d8c1-4ac7-b9ac-d580cd22aa1d")
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Due", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Dues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b34e20b9-7f7c-49e4-964a-324fabb52f05"),
                            Amount = 750m,
                            ApartmentId = new Guid("8c38f383-b67d-4f6c-8a75-ff57c58621b5"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Month = 1,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("9873d671-211a-4c52-a98c-39e7f8afba30"),
                            Amount = 750m,
                            ApartmentId = new Guid("b2823418-628c-4bce-848a-4032abb0feaf"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Month = 1,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("baa7a46e-8745-4525-abfa-512ceb5e20e6"),
                            Amount = 850m,
                            ApartmentId = new Guid("825472e5-0820-46cd-9039-b1565befd726"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Month = 1,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a153ea7-321a-4f30-ab2d-1bafd40d0b76"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hasan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Güvenlik",
                            Phone = "05551112233",
                            Position = "Security",
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("65470101-88dc-4ff4-ac60-6e9a02035f51"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nurcan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Temizlik",
                            Phone = "05554445566",
                            Position = "Cleaning Staff",
                            SiteId = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            StartDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueId");

                    b.HasIndex("PayerId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fa465d5-c762-43ee-b893-67e9e88f963e"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueId = new Guid("b34e20b9-7f7c-49e4-964a-324fabb52f05"),
                            IsDeleted = false,
                            PaidAmount = 750m,
                            PayerId = new Guid("44010978-e210-4db8-81e9-6f191695953b"),
                            PaymentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bank Transfer",
                            PaymentStatus = 1
                        },
                        new
                        {
                            Id = new Guid("3a231a48-7119-475a-8dcf-c62ec7cac700"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueId = new Guid("9873d671-211a-4c52-a98c-39e7f8afba30"),
                            IsDeleted = false,
                            PaidAmount = 750m,
                            PayerId = new Guid("e60285cb-58df-4960-ba9f-d5bbd5116195"),
                            PaymentDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = 2
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Sites", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0bc1c34-dbd4-4bd7-9668-d8c6c66ed480"),
                            Address = "Atatürk Cad. No:12",
                            City = "İstanbul",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            Name = "Yeşilvadi Sitesi"
                        },
                        new
                        {
                            Id = new Guid("ef55ed67-b6ae-4746-8b94-6e48a0f61a49"),
                            Address = "Cumhuriyet Bulvarı No:45",
                            City = "Ankara",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = new Guid("cc25344a-3173-4459-9ad4-d2c7d7a5ac13"),
                            Name = "Mavi Köşk Sitesi"
                        });
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegisteredById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("RegisteredById");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Announcement", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppUser", null)
                        .WithMany("Announcements")
                        .HasForeignKey("AppUserId");

                    b.HasOne("SiteManagement.Entity.Entities.Site", "Site")
                        .WithMany("Announcements")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Apartment", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Block", "Block")
                        .WithMany("Apartments")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "Owner")
                        .WithMany("OwnedApartments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SiteManagement.Entity.Entities.Site", "Site")
                        .WithMany("Apartments")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "Tenant")
                        .WithMany("RentedApartments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Block");

                    b.Navigation("Owner");

                    b.Navigation("Site");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserClaim", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserLogin", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserRole", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUserToken", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Block", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Site", "Site")
                        .WithMany("Blocks")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Complaint", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Apartment", "Apartment")
                        .WithMany("Complaints")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Due", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Apartment", "Apartment")
                        .WithMany("Dues")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Employee", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Site", "Site")
                        .WithMany("Employees")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("SiteManagement.Entity.Entities.Employee", "UserId");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Payment", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Due", "Due")
                        .WithMany("Payments")
                        .HasForeignKey("DueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Due");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Site", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Vehicle", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Apartment", "Apartment")
                        .WithMany("Vehicles")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Visitor", b =>
                {
                    b.HasOne("SiteManagement.Entity.Entities.Apartment", "Apartment")
                        .WithMany("Visitors")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteManagement.Entity.Entities.AppUser", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("RegisteredBy");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Apartment", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Dues");

                    b.Navigation("Vehicles");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Complaints");

                    b.Navigation("Employee");

                    b.Navigation("OwnedApartments");

                    b.Navigation("RentedApartments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Block", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Due", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SiteManagement.Entity.Entities.Site", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Apartments");

                    b.Navigation("Blocks");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
